### ISSUE TITLE
Unhandled Exception: System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by afisd** [afisd/jovice#1]
> 16/02/25 00:15:19.879|ME2-A-JWB-CCD|Checking Interface
> 
> Unhandled Exception: System.ArgumentOutOfRangeException: startIndex cannot be la
> rger than length of string.
> Parameter name: startIndex
>    at System.String.InternalSubStringWithChecks(Int32 startIndex, Int32 length,
> Boolean fAlwaysCopy)
>    at System.String.Substring(Int32 startIndex)
>    at Jovice.Probe.MEProcess() in D:\Projects\Share\Jovice.Common\Necrow\MEProbe
> .cs:line 2319
>    at Jovice.Probe.MainLoop() in D:\Projects\Share\Jovice.Common\Necrow\Probe.cs
> :line 513
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
> ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
> ontextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
> ontextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart()
>

**Comment by afisd** [comment]
Fixed with line length check:
```
                                    if (line.Length > 58)
                                        description.Append(line.Substring(58).TrimStart());
```
