### ISSUE TITLE
KeyNotFoundException

### ISSUE THREAD

**Issue by adrianir** [afisd/jovice#12]
```
Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given
key was not present in the dictionary.
   at System.Collections.Generic.SortedDictionary`2.get_Item(TKey key)
   at Jovice.Probe.MEProcess() in D:\Projects\jovice\Jovice.Common\Necrow\MEProb
e.cs:line 2703
   at Jovice.Probe.MainLoop() in D:\Projects\jovice\Jovice.Common\Necrow\Probe.c
s:line 1015
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by afisd** [comment]
I am not sure why this error happened, the parentPort variable should exists in the check bracket. I will add another check before enter the MEInterfaceToDatabase bracket to add additional checks.
