### ISSUE TITLE
KeyNotFoundException

### ISSUE THREAD

**Issue by adrianir** [afisd/jovice#13]
```
2016/06/16 18:01:44.217|ME-D2-BLJ|Request completed (1247 lines in 0.334s)
2016/06/16 18:01:44.224|ME-D2-BLJ|Request [show service sap-using]...
2016/06/16 18:01:45.296|ME-D2-BLJ|Request completed (921 lines in 0.321s)

Unhandled Exception: System.Collections.Generic.KeyNotFoundException: The given
key was not present in the dictionary.
   at System.Collections.Generic.SortedDictionary`2.get_Item(TKey key)
   at Jovice.Probe.MEProcess() in D:\Projects\jovice\Jovice.Common\Necrow\MEProb
e.cs:line 2703
   at Jovice.Probe.MainLoop() in D:\Projects\jovice\Jovice.Common\Necrow\Probe.c
s:line 1015
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo
ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C
ontextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

**Comment by afisd** [comment]
Duplicated with #12
